version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./frontend/public:/app/frontend/public
    restart: unless-stopped
    networks:
      - rtm_network

  frontend_tc:
    build: ./frontend
    environment:
      PORT: 3001
    volumes:
      - ./frontend/public:/app/public
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-tc.rule=Host(`cinephoria.fr`, `www.cinephoria.fr`)"
      - "traefik.http.routers.frontend-tc.entrypoints=websecure"
      - "traefik.http.routers.frontend-tc.tls=true"
      - "traefik.http.routers.frontend-tc.tls.certresolver=myresolver"
      - "traefik.http.services.frontend-tc.loadbalancer.server.port=3001"
      - "traefik.http.services.frontend-tc.loadbalancer.passHostHeader=true"
      - "traefik.http.routers.frontend-tc-http.rule=Host(`cinephoria.fr`, `www.cinephoria.fr`)"
      - "traefik.http.routers.frontend-tc-http.entrypoints=web"
      - "traefik.http.middlewares.redirect-to-https-tc.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https-tc.redirectscheme.permanent=true"
      - "traefik.http.routers.frontend-tc-http.middlewares=redirect-to-https-tc"
      - "traefik.http.middlewares.www-redirect-tc.redirectregex.regex=^https://www\\.(.+)"
      - "traefik.http.middlewares.www-redirect-tc.redirectregex.replacement=https://$${1}"
      - "traefik.http.middlewares.www-redirect-tc.redirectregex.permanent=true"
      - "traefik.http.routers.frontend-tc.middlewares=www-redirect-tc"
      - "traefik.http.middlewares.security-headers-tc.headers.customResponseHeaders.Strict-Transport-Security=max-age=31536000; includeSubDomains; preload"
      - "traefik.http.middlewares.security-headers-tc.headers.customResponseHeaders.X-Content-Type-Options=nosniff"
      - "traefik.http.middlewares.security-headers-tc.headers.customResponseHeaders.X-Frame-Options=DENY"
      - "traefik.http.middlewares.security-headers-tc.headers.customResponseHeaders.X-XSS-Protection=1; mode=block"
      - "traefik.http.routers.frontend-tc.middlewares=security-headers-tc,www-redirect-tc"
    networks:
      - rtm_network

networks:
  rtm_network:
    external: true
    name: traefik_proxy 